# Generated by Django 4.0.3 on 2022-06-05 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Data',
        ),
    ]
