# Generated by Django 4.0.3 on 2022-06-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_data_content_score_data_grammar_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='grammar_matches',
            field=models.TextField(blank=True, null=True),
        ),
    ]
