# Generated by Django 4.0.3 on 2022-06-06 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_data_mechanics_word'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='mechanics_word',
            new_name='mechanics_words',
        ),
    ]
