# Generated by Django 4.0.3 on 2022-06-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_rename_mechanics_word_data_mechanics_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='mechanics_words',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
