# Generated by Django 4.0.3 on 2022-06-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_alter_data_mechanics_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='style_expressions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
