# Generated by Django 4.0.3 on 2022-06-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_data_style_expressions'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='lexical_complexity_words',
            field=models.TextField(blank=True, null=True),
        ),
    ]
