# Generated by Django 4.0.3 on 2022-06-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_data_content_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='content_val',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='grammar_val',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='mechanics_val',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='plagiarism_val',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='style_val',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='vocabulary_val',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
