# Generated by Django 4.0.3 on 2022-06-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_data_content_val_data_grammar_val_data_mechanics_val_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='content_val',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='grammar_val',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='mechanics_val',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='plagiarism_val',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='style_val',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='vocabulary_val',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
